version: '2'
services:
  zookeeper:
    image: confluent/cp-zookeeper:latest
    network_mode: host
    environment:
      - ZOOKEEPER_CLIENT_PORT: 32181
      - ZOOKEEPER_TICK_TIME: 2000
    
  kafka:
    image: confluent/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_ID: 1
      - KAFKA_ZOOKEEPER_CONNECT: burberrypi.local:32181
      - KAFKA_ADVANCED_LISTENERS: PLAINTEXT://burberyypi.local:29092